name: lluvia
description: App lluvia de texto
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  device_info_plus: ^11.3.3
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  async: ^2.12.0
  android_intent_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  leak_tracker: ^10.0.8

flutter:
  uses-material-design: true

